In [5]:
import  mysql.connector as mySQL

In [7]:
config = {
    'host': 'localhost',
    'user':'root',
    'password':'root',
    'database':'employees'
}

In [8]:
try:
    conn = mySQL.connect(**config)
    cursor = conn.cursor()
    query = "SELECT * FROM emp"
    cursor.execute(query)
    rows= cursor.fetchall()
    for row in rows:
        print(row)
except mySQL.Error as err:
    print(f"Error: {err}")
finally:
    if 'cursor' in locals():
        cursor.close()
    if 'conn' in locals() and conn.is_connected():
        conn.close()

(1, 'hyder', 30, 'm')
(2, 'naveed', 35, 'm')
(3, 'fatima', 40, 'f')
(4, 'hyder', 30, 'M')
(5, 'naveed', 35, 'M')
(6, 'fatima', 40, 'F')

In [9]:
rows

[(1, 'hyder', 30, 'm'),
 (2, 'naveed', 35, 'm'),
 (3, 'fatima', 40, 'f'),
 (4, 'hyder', 30, 'M'),
 (5, 'naveed', 35, 'M'),
 (6, 'fatima', 40, 'F')]

In [13]:
import pandas as pd
pd.DataFrame(rows) 
# The above code connects to a MySQL database, retrieves all records from the 'emp' table, and prints them.

   0       1   2  3
0  1   hyder  30  m
1  2  naveed  35  m
2  3  fatima  40  f
3  4   hyder  30  M
4  5  naveed  35  M
5  6  fatima  40  F

In [14]:
columns=['id','name','age','gender']

In [15]:
pd.DataFrame(rows, columns=columns)

   id    name  age gender
0   1   hyder   30      m
1   2  naveed   35      m
2   3  fatima   40      f
3   4   hyder   30      M
4   5  naveed   35      M
5   6  fatima   40      F